---
settings:
  name: Astra Control Center
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: release-notes/whats-new.html
  versions:
  - version-number: '23.07'
    url: "/astra-control-center-2307"
  - version-number: '24.02'
    url: "/astra-control-center"
  - version-number: '23.10'
    url: "/astra-control-center-2310"
  - version-number: '23.04'
    url: "/astra-control-center-2304"
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: Astra Control Center 23.07 文件
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: concepts
  - section: use
  - section: rest-api
  - section: support
  - title: 舊版
    url: "/acc-earlier-versions.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: Astra
  repo: astra-family
